language: java
dist: jammy
jdk:
 - openjdk17
notifications:
  email:
    recipients:
      - alondo1@students.towson.edu
    on_success: always # default: change
    on_failure: always # default: always
